name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Display structure of downloaded files
        run: ls -R
