name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - run: gh release create "$TAG" ./apk/**/*.apk
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ inputs.tag }}
